language: swift

branches:
  only:
   - master

xcode_project: Flowter.xcodeproj
xcode_scheme: Flowter
osx_image: xcode10.1
xcode_sdk: iphonesimulator12.1

before_install:
  - gem install cocoapods
  - pod repo update
  
script:
  - pod install
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Flowter.xcworkspace -scheme FlowterDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
  - pod lib lint --allow-warnings
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Flowter'