language: swift

branches:
  only:
   - master

xcode_project: Flowter.xcodeproj
xcode_scheme: Flowter
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install
  
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Flowter.xcworkspace -scheme Flowter -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint